- name:  Defined variable in another file and accessing at task level
  hosts:  all
  connection:  local
  tasks:
    - name:  Defined variable in another file and accessing at task level
      ansible.builtin.debug:
        msg:  SSS == {{fff}}
      include_vars:
        - file1.yml
