- name: declaring variable at play level
  hosts: all
  connection: local
  vars:
    abc: example.play.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: xyz == {{abc}}

- name:  Declaring variable at task level
  hosts:  all
  connection:  local
  tasks:
    - name:  declaring variable at play level and accessing at play level
      ansible.builtin.debug:
        msg: abc == {{klm}}
      vars:
        klm:  example.task.com