- name: declaring variable at play level
  hosts: all
  connection: local
  vars:
    abc: example.play.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: xyz == {{abc}}

- name:  Declaring variable at task level
  hosts:  all
  connection:  local
  tasks:
    - name:  declaring variable at task level and accessing at task level
      ansible.builtin.debug:
        msg: abc == {{klm}}
      vars:
        klm:  example.task.com

- name:  Declared variable in another file and accessing at play level
  hosts:  all
  connection:  local
  vars_files:
    - files.yml
  tasks:
    - name:  accessing variable at task level
      ansible.builtin.debug:
        msg:  mnm == {{efg}}

- name:  Declared variable in another file and accessing at play level
  hosts:  all
  connection:  local
  vars_files:
    - file1.yml
  tasks:
    - name:  accessing variable at task level
      ansible.builtin.debug:
        msg:  sss == {{fff}}
